substitutions:
  name: esp8266-ups-ali
  device_description: "Monitor and control a APC UPS via RS232"
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "colin.esphome-apc-ups"
    version: 1.1.0

esp8266:
  board: d1_mini

external_components:
  - source: github://ccpengcolin-rgb/esphome-apc-ups
    components: [apc_ups]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: "793b789912cdcf28f34d83f67f8764cc"

web_server:
  port: 80

logger:
  baud_rate: 0 # 禁用UART日志以避免干扰UPS通信

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:
  encryption:
    key: "XpCbGDHibA4439rW5+pZVolROuOfrjxFeDzXqvU9aDo="

uart:
  - id: uart_0
    baud_rate: 2400
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

apc_ups:
  - id: apc_ups1
    uart_id: uart_0
    update_interval: 60s

# Q2命令相关数值传感器
sensor:
  - platform: apc_ups
    apc_ups_id: apc_ups1
    ups101:
      name: "UPS101 Line Voltage"
    ups102:
      name: "UPS102 Line Frequency"
    ups103:
      name: "UPS103 Output Voltage"
    ups104:
      name: "UPS104 Output Current"
    ups105:
      name: "UPS105 Output Power"
    ups106:
      name: "UPS106 Battery Voltage"
    ups107:
      name: "UPS107 Battery Temperature"
    ups113:
      name: "UPS113 Load Percentage"
    ups114:
      name: "UPS114 Battery Capacity"
    ups115:
      name: "UPS115 Estimated Runtime"
    ups116:
      name: "UPS116 Input Voltage"
    ups117:
      name: "UPS117 Output Voltage 2"
    ups118:
      name: "UPS118 Unknown"

# Q2命令相关二进制传感器
binary_sensor:
  - platform: apc_ups
    apc_ups_id: apc_ups1
    ups108:
      name: "UPS108 Utility Fail"
    ups109:
      name: "UPS109 Battery Low"
    ups110:
      name: "UPS110 Overload"
    ups111:
      name: "UPS111 Fault"
    ups112:
      name: "UPS112 Test In Progress"
